services:
  apache-php:
    build:
      context: .
      dockerfile: .docker/apache-php/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log/apache2
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
      - seq
    environment:
      - SEQ_LOG_HOST=seq    
    ports:
      - '8000:80'
    networks:
      - internal
    logging:
      driver: gelf 
      options: 
        gelf-address: udp://localhost:12201  
  mariadb:
    image: mariadb:lts
    volumes:
      - .docker/mariadb/data:/var/lib/mysql:Z
    restart: unless-stopped
    environment:
     - MARIADB_ROOT_PASSWORD=docker
     - MARIADB_USER=wordpress
     - MARIADB_PASSWORD=wordpress
     - MARIADB_DATABASE=wordpress
    ports:
      - '3306:3306'
    networks:
      - internal
  adminer:
    image: dockette/adminerevo:latest
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
      - ADMINER_DEFAULT_DB=wordpress
    depends_on:
      - mariadb 
    ports: 
      - '8001:8080'
    networks:
      - internal
  redis:
    image: ubuntu/redis:latest
    restart: unless-stopped
    ports: 
      - '6379:6379'
    environment:
      - TZ=America/Sao_Paulo
      - REDIS_PASSWORD=docker  
    networks:
      - internal 
  seq:
    image: datalust/seq:latest
    restart: unless-stopped
    volumes:
      - ./logs:/data
    ports:
      - '8002:80'
      - '12201:12201/udp'
    environment:
      - ACCEPT_EULA=Y
      #- SEQ_FIRSTRUN_ADMINPASSWORDHASH="docker"
    networks:
      - internal                  

networks:
  internal:
    driver: bridge